### ISSUE TITLE
Aria2 files not deleted upon completion

### ISSUE THREAD

**Issue by Ano-Nymus** [hugetiny/negibox#10]
Bug 5:
The following error appeared in version 0.1.7 of your amd64 appimage release:

Aria2 files are not deleted upon successful completion of task.
This behavior changed compared to 0.1.2 - 0.1.5, making me believe it is a bug.
The original behavior seems more logical, given that aria2 files are unnecessary upon completion.

**Comment by hugetiny** [comment]
Aria2 uses a control file to track the progress of a download. A control file is placed in the same directory as the downloading file and its file name is the file name of downloading file with .aria2 appended.

If the .aria2 file is deleted,Negibox can not track the infos of completed tasks in Finished / Stopped section.In this case,users cannot double click to open the file in Negibox.I think i need to make a pull request to aria2 to add the function of configuring custom path of .aria2 files.

**Comment by Ano-Nymus** [comment]
In this case, what happenes if the file is removed? Would the aria control file be stored indefinitley?
The current behavior keeps the aria file even after a task is removed, which still sounds like a bug.

**Comment by hugetiny** [comment]
if the .aria2 file is removed, users can't see the finished tasks info in Finished / Stopped after they restart Negibox cause aria2 can't list a finished task without the .aria2 control file. It's inconvenient for users to find downloaded files folder by folder.

 the .aria2 file should be stored in other hidden folders in the future,so users could always open files in Negibox

**Comment by Ano-Nymus** [comment]
Clarification: 
I understand that it makes sense for negibox to keep the aria files after a download has been finished.
However, the aria2 files must be deleted after all entrys of a Task/Download have been removed, !including! finished tasks info in Finished / Stopped. 

That means:
Aria2 files must be deleted after the user removed the original download from the success history, as he has no way to open the task thereafter. 
This stays true if aria2 files are placed in a seperate tmp directory, as Negibox would otherwise accumulate more and more aria2 files, potentially filling up the disc.

**Comment by hugetiny** [comment]
.aria2 file will be removed in 0.2.0
