### ISSUE TITLE
Too many settings menus

### ISSUE THREAD

**Issue by Ano-Nymus** [hugetiny/negibox#11]
Issue 2:
The following issue appeared in version 0.1.7 of your amd64 appimage release:

The current program features a "Settings" menu, as well as an "Advanced Settings" menu.
This much is completley understandable.
 
The "Advanced Settings" menu splits into 8 different submenus, all labeled "XXX" Settings. 
Not only is this an unnessecary use of the word settings, 
with submenus of the menu Advanced "Settings" still being called "Settings",
it also includes both "General Settings" and "Advanced Settings".
Advanced Settings should never contain "General Settings" for obvious reasons,
and adding the submenu Advanced Settings into the menu Advanced Settings is plain redundant.

I recommend merging/renaming/removing these menus.

**Comment by hugetiny** [comment]
Will be fixed in 0.1.9

**Comment by hugetiny** [comment]
@Ano-Nymus Feel free to reopen this issue when you feel settings menus text need to improve.
