### ISSUE TITLE
Mac OS 下permission deny 错误 

### ISSUE THREAD

**Issue by jk50505k** [hugetiny/negibox#13]
<img width="279" alt="image" src="https://user-images.githubusercontent.com/38711478/51798376-e6b4a200-224b-11e9-9700-ed3e2d4a2643.png">
<img width="1136" alt="image" src="https://user-images.githubusercontent.com/38711478/51798384-04820700-224c-11e9-952e-0ade3e4dc2e6.png">
<img width="1136" alt="image" src="https://user-images.githubusercontent.com/38711478/51798393-31ceb500-224c-11e9-93da-df05a9ddf4d7.png">

**Comment by jk50505k** [comment]
更换到其他目录也没有用

**Comment by hugetiny** [comment]
@jk50505k  /~这个路径有点怪，是你手动设的吗？请提供下版本号
另外有没有弹窗报错，有的话提供一下

**Comment by jk50505k** [comment]
@hugetiny  
<img width="396" alt="image" src="https://user-images.githubusercontent.com/38711478/51800469-078bf000-226a-11e9-9d7d-b7454d826329.png">
<img width="583" alt="image" src="https://user-images.githubusercontent.com/38711478/51800472-11adee80-226a-11e9-877a-adfe8356d784.png">
默认路径失败后我才更换的,所有路径都是这个结果<br>
没有弹窗报错

**Comment by hugetiny** [comment]
0.1.9会换成目录选择，避免手动输入路径错误。图标看上去也不正常，你现在暂时可以输入正确的绝对路径试试。

**Comment by hugetiny** [comment]
@jk50505k 已经在0.2.0中修复
