### ISSUE TITLE
如何为项目开发提供帮助

### ISSUE THREAD

**Issue by longwusha** [hugetiny/negibox#16]
从代码结构来看，本项目为negibox官网源码，而非negibox下载工具的源码。这意味着这其实是一个闭源工具吗？如果我们希望为项目的特性开发或bug修复提供帮助，我们应该怎么做？

**Comment by hugetiny** [comment]
我也考虑过是否开源，目前实际情况是我投入了全部精力上去，如果初期开源可能我的想法很快就会凉。抱歉，目前也没有开源的计划。当然Negibox一直且永远是免费的。
目前项目的语言文字翻译部分开源的，后续会慢慢考虑部分开源，但是不会全部开源。

**Comment by xiashali** [comment]
Aria2 采用了 GPLv2, 你的行为违反了 GPLv2 协议。请立即停止你的侵权行为。

> `This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version.`
