### ISSUE TITLE
macos pemission deny

### ISSUE THREAD

**Issue by shengtaolee** [hugetiny/negibox#18]
系统版本: macos 10.14.3

问题:
Engine Settings->通用设置->下载路径, 设置好之后无法保存,始终是 / ,然后下载文件permission deny

**Comment by rxctp** [comment]
同样的问题

**Comment by hugetiny** [comment]
马上加急修复

On Feb 14, 2019, at 6:41 PM, rxctp <notifications@github.com<mailto:notifications@github.com>> wrote:


同样的问题

**Comment by hugetiny** [comment]
@rxctp @shengtaolee  已经在0.2.0中修复
