### ISSUE TITLE
Entrys (Downloading \ Finished/Stopped) dissapear until restart

### ISSUE THREAD

**Issue by Ano-Nymus** [hugetiny/negibox#2]
First of, great Work! It is rare to see a program work this well early on.
The following error appeared in version 0.1.2 of your amd64 appimage release:

All entrys dissapear after downloading from "http://coolrom.com.au",
and no entrys can be added. This turns the programm useless until restart.

This bug is generally only triggerred after around 1 hour or more of continuus usage,
which makes me believe it might be related to the mentioned site using links that are only valid for a given time. The links will stay valid as long as the bug is not triggered.

**Comment by Ano-Nymus** [comment]
This bug appears to be fixed as of 0.1.7. I will perform further testing and remark if it reappears.

**Comment by Ano-Nymus** [comment]
I confirm that the bug has dissapeared starting with 0.1.7

**Comment by Ano-Nymus** [comment]
The bug has reappeared, starting with version 0.1.9. 

I will test whether or not it reappeared in older version as well, thus indicating that it is related to the prior re-installation of my operating system, and not negibox itself.

**Comment by Ano-Nymus** [comment]
Issue returned in 0.1.8, which proves it never dissapeared, i just did not see it.
The following snapshots showcase the situation after the bug has been triggered. Entrys are no longer visible:
![missing entrys 1](https://user-images.githubusercontent.com/44923919/51872821-b0157f00-2352-11e9-91cf-082f48e0e020.png)
![missing entrys 2](https://user-images.githubusercontent.com/44923919/51872824-b146ac00-2352-11e9-9dae-c0ebf94a92d3.png)

It is of note that i started the program using the terminal, and that i do not see any terminal error,
it does however always end after showing the download summary, after which no further output is shown. The bug also stops all file downloads, as is seen by missing terminal output and files not getting any larger.

**Comment by hugetiny** [comment]
Fixed in 0.2.4
