### ISSUE TITLE
最新0.22版安装失败

### ISSUE THREAD

**Issue by ghost** [hugetiny/negibox#25]
WIN7 64位 旗舰版系统

![qq 20190303174740](https://user-images.githubusercontent.com/14135584/53693538-d2307000-3ddc-11e9-817b-0dbebafd2f8a.png)

**Comment by ghost** [comment]
重启电脑并重新下载安装，一切正常。

**Comment by hugetiny** [comment]
这个有可能是下载文件不完整导致的。我自己也很难从github release上直接下载下来，经常失败

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: daxiaopipi <notifications@github.com>
发送时间: Sunday, March 3, 2019 7:52:14 PM
收件人: hugetiny/negibox
抄送: Subscribed
主题: Re: [hugetiny/negibox] 最新0.22版安装失败 (#25)


重启电脑并重新下载安装，一切正常。

―

**Comment by hugetiny** [comment]
下一步会考虑换静态托管方式
