### ISSUE TITLE
Auto-Update renames File

### ISSUE THREAD

**Issue by Ano-Nymus** [hugetiny/negibox#3]
Bug 2:
The following error appeared during auto-update from version 0.1.2 to version 0.1.7 of your amd64 appimage release:

The Autoupdater renames the appimage file, which can lead to confusion, especially if the file was originally in an unorganized folder. The new name is: "update.AppImage"

**Comment by hugetiny** [comment]
Which GUI did you install on Linux
I think the desktop option in electron could solve this under certain condition（Users always click the shortcut with Negibox icon）
but the docs in [electron builder](https://www.electron.build/generated/appimage-options.html) was too simple to understand
```
desktop any - The Desktop file entries (name to value).
```
I'm working on it

**Comment by Ano-Nymus** [comment]
Mate Desktop, though i started negibox using the terminal.
Clarification: I never added a shortcut, it is the appimage itself that was renamed.

**Comment by hugetiny** [comment]
This will be fixed in 0.2.0

**Comment by hugetiny** [comment]
@Ano-Nymus  The desktop file(shortcut in Applications) is included since 0.2.3.AppImage can be considered as an setup file
