### ISSUE TITLE
Linux, appimage, Javascript error

### ISSUE THREAD

**Issue by salvadhor** [hugetiny/negibox#33]
Due to well known error https://github.com/hugetiny/negibox/issues/28 I had to manually edit ~/.Nagiboxc/Negiboxc.conf and correct max-connection value. For unknown reason default is 256, while Negibox expects something between 1 - 16:

(...)
max-connection-per-server=4
(...)

Issue still appears in 0.2.7.

**Comment by hugetiny** [comment]
max-connection value will be 16 since 0.2.8

**Comment by hugetiny** [comment]
@salvadhor Negibox is now open-source and refactoring
