### ISSUE TITLE
windows上 基本的下载功能都不具备。

### ISSUE THREAD

**Issue by kaweizz** [hugetiny/negibox#37]
新建
复制下载链接 
立即下载
按钮无效

点击系统设置报错
不知道是不是没适配1903

浏览器扩展没有找到。。readme里面没有。

最后没有便携版...

测试环境：
18362.207 
negibox-setup-0.2.7.exe

**Comment by kaweizz** [comment]
综上所述。。基本没什么用.. 150MB ...

**Comment by hugetiny** [comment]
@kaweizz 我最近在做手机版 争取各个版打通，便携版我要看一下electron-builder怎么弄。

**Comment by hugetiny** [comment]
应该跟windows版本关系不大

**Comment by hugetiny** [comment]
无法安装的话，注意一下自己的系统，32位 64位不要弄错
