### ISSUE TITLE
Translation Incomplete

### ISSUE THREAD

**Issue by Ano-Nymus** [hugetiny/negibox#4]
Bug 3:
The following error appeared in version 0.1.7 of your amd64 appimage release:

All translations except English appear incomplete and fallback to chinese/eastern language. The fallback-language should be changed to english.

**Comment by hugetiny** [comment]
fallback will be fixed in 0.1.8.
the translation file is published in the code base.please help me to translate to other language if you like.

**Comment by Ano-Nymus** [comment]
I will continue to translate once 0.1.9 is out, as you plan to change the settings layout.

**Comment by hugetiny** [comment]
Negibox is now open-source and I am working on refactoring with Quasar. Vue-i18n  is a mature framework and will not contain translation errors.
