### ISSUE TITLE
No way to view version

### ISSUE THREAD

**Issue by Ano-Nymus** [hugetiny/negibox#5]
Issue 1:
The following issue appeared in version 0.1.7 of your amd64 appimage release:

There is no "about" page and no way to view the current version, which should be adressed.
This becomes more problematic with bug 3 (https://github.com/hugetiny/negibox/issues/3), as there is no way to know if the updater worked, or which version is in use, unless comparing sizes.

**Comment by Ano-Nymus** [comment]
Note: It is possible to view the version using the terminal output, but this should not be expected from the user, as he is more likely to run the program via gui.

**Comment by hugetiny** [comment]
Thank you for your advice,the "about" page for linux will be added in 0.1.18

**Comment by Ano-Nymus** [comment]
The current implementation of the about page is still unfinished.
It should ideally be called about, show an image of negibox, the current version directly below, 
and then a short description of what the program is supposed to do, like:

""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
![image](https://user-images.githubusercontent.com/44923919/51689159-63e6d980-1ff6-11e9-95a8-15d06b88fe59.png)
<h1><b>Negibox Version 0.1.8</b></h1>

Negibox is the best free cross-platform(Mac,Windows,Linux,Android,iOS)downloader for everyone in the world. Support http https ftp sftp ftps magnet BitTorrent MetaLink. https://negibox.com

""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""

**Comment by hugetiny** [comment]
@Ano-Nymus In 0.2.2 version will show in title bar and I will remove the menubar for Windows and Linux

**Comment by hugetiny** [comment]
fixed
