### ISSUE TITLE
选取种子之后无法下载

### ISSUE THREAD

**Issue by mkblbj** [hugetiny/negibox#7]
<img width="1136" alt="screen shot 2019-01-21 at 10 05 01 pm" src="https://user-images.githubusercontent.com/32349794/51479232-a1feb600-1dc8-11e9-8daa-d7b50643fc7c.png">

**Comment by hugetiny** [comment]
将会在0.1.8修复

**Comment by hugetiny** [comment]
@mkblbj 试一试 应该行了

**Comment by mkblbj** [comment]
又发现个问题选取磁力链接下载完成后，应该只会下载种子，并且保存，但是下载路径并没有看到。

<img width="1290" alt="screen shot 2019-02-03 at 2 39 33 pm" src="https://user-images.githubusercontent.com/32349794/52173551-a14f2200-27c1-11e9-8a61-dfb56c5a75c4.png">
